### PR TITLE
Don't force overwriting displayName with styled components

### PR DESCRIPTION
**Pull request by giuband**
1) It makes the bundle bigger
2) We don't really need it anymore since we started testing components with `react-testing-library`
3) It exposes internal naming conventions

### CODE REVIEW

**Comment by Gpx** [comment]
The thing is that if we don't write the `displayName` in the react inspect tool we can't identify the component

**Comment by giuband** [comment]
I know, but does it really help that much? Especially for very small components used only in a place.
I wouldn't remove the line `Layout.displayName = 'Layout'`, but I would remove `BigButton.displayName = 'BigButton'`

**Comment by Gpx** [comment]
Is there a way to add or remove them automatically?

**Comment by giuband** [comment]
Not that I know

**Comment by ivan-navarro-75** [comment]
for designers it is sometimes a helpful to give the components a name, a few days ago @northswiss was just asking me why not all components were properly named.

**Comment by moritztk** [comment]
1. Can you give a figure by how much? So we can make an educated decision?
3. How so? Are the displaynames shipped somehow?

**Comment by giuband** [comment]
1) It's impossible to do that. Imagine considering even only the cases where we have an unused styled component that gets not detected as unused just because we are overwriting the display name

**Comment by moritztk** [comment]
@giuband did you add a trello ticket as well for this?
Otherwise we might miss it in the guild.

**Comment by northswiss** [comment]
A bit late to the party, but from a design side it is really helpful to debug and review layout etc in the React inspector with the displayNames. It can be a real time-saver. How much "cost" this adds in terms of KBs I don't know but it definitely saves time.

**Comment by giuband** [comment]
@northswiss I closed the PR because `styled-components v4` (which has been released today) will provide ways of automatically showing the display name of the component in development mode without having to manually assign it. As soon as we migrate to it I'll make sure it works as expected

**Pull request closed without merging**
